version: '3.8'

services:

  # Kong Gateway (DB-less mode)
  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"   # Kong Proxy
      - "8001:8001"   # Kong Admin API
      - "8002:8002"   # Kong Manager (GUI)
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
    networks:
      - api-gateway-network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  users-service:
    build: ./app1-users
    container_name: users-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-gateway-network

  products-service:
    build: ./app2-products
    container_name: products-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-gateway-network

  orders-service:
    build: ./app3-orders
    container_name: orders-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-gateway-network

  orders-service-v2:
    build: ./app4-orders-v2
    container_name: orders-service-v2
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge